C++ header: fix clang compilation of pi_mutex and pi_cond ctors
When a C++ application is built with librtpi and compiled with

     /usr/bin/clang++ -std=c++17 -I${HOME}/librtpi/src ${HOME}/librtpi/src/.libs/librtpi.a . . .

the following errors appear:

    In file included from ${HOME}/librtpi/src/rtpi/condition_variable.hpp:9:
    In file included from ${HOME}/librtpi/src/rtpi.h:13:
        ${HOME}/librtpi/src/rtpi_internal.h:24:19: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
	   24 |         return pi_mutex{ 0, f };
	      |                          ^~~~
	      |                          {   }
        ${HOME}/librtpi/src/rtpi_internal.h:51:18: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
           51 |         return pi_cond{ 0, f, 0, RTPI_COND_STATE_READY };
	      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	      |                         {                             }
    2 errors generated.
    make: *** [Makefile:111: condvar-rtpi_lib_test-tsan] Error 1

Fix these errors by adding the missing braces.

Signed-off-by: Alison Chaiken <alison@she-devel.com>